export default [
  {
    files: ["**/*.ts", "**/*.tsx"],
    ignores: [
      "node_modules/**",
      "dist/**",
      "build/**",
      ".sst/**",
      "packages/*/dist/**",
      "packages/*/build/**",
      "sdks/vscode/**",
    ],
  },
  {
    rules: {
      "no-console": "warn",
      "no-debugger": "error",
      "no-alert": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-void": "error",
      "no-with": "error",
      "prefer-const": "error",
      "prefer-arrow-callback": "error",
      "arrow-spacing": "error",
      "no-duplicate-imports": "error",
      "no-useless-return": "error",
      "no-else-return": "error",
      "no-lonely-if": "error",
      "no-unneeded-ternary": "error",
      yoda: "error",
      curly: "error",
      eqeqeq: "error",
      "no-throw-literal": "error",
      "prefer-promise-reject-errors": "error",
      "require-await": "error",
      "no-return-await": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-trailing-spaces": "error",
      "no-multiple-empty-lines": ["error", { max: 2 }],
      "eol-last": "error",
      "comma-dangle": ["error", "never"],
      semi: ["error", "never"],
      quotes: ["error", "single", { avoidEscape: true }],
      indent: ["error", 2, { SwitchCase: 1 }],
    },
  },
]
